spring.application.name=sctec-enterprise-management-challenge

# 1. Configurações de Conexão (Cria um banco em memória chamado 'sctecdb')
spring.datasource.url=jdbc:h2:mem:sctec_enterprise_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configurações do Hibernate (Faz o Java criar as tabelas automaticamente)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 3. Console do H2 (Ver o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. Mostrar o SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true